[package]
name = "msgbus"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
chrono.workspace = true
ustr.workspace = true
common = {path = "../common"}