[package]
name = "backtest"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
tokio.workspace = true
ustr.workspace = true
common = {path = "../common"}
msgbus = {path = "../msgbus"} 
rand = "0.8.5"
